run:
  timeout: 5m
  go: '1.23'

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - gofmt

linters-settings:
  errcheck:
    check-type-assertions: false
