global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alerting rules file
rule_files:
  - "alert_rules.yml"

scrape_configs:
  # Prometheus scrapes itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape local app (for local dev)
  - job_name: 'go-devops-app-local'
    static_configs:
      - targets: ['app:8080']
    metrics_path: '/metrics'

  # Scrape the LIVE AWS app through ALB
  - job_name: 'go-devops-app-aws'
    static_configs:
      - targets: ['go-devops-app-alb-244164610.us-east-1.elb.amazonaws.com']
    metrics_path: '/metrics'
    scheme: http
